## makeCacheMatrix and cacheSolve take values and arguments for a square matrix 'x', search to see if an existing inverse square matrix exists and, if not, generate and cache an inverse square matrix. 

## makeCacheMatrix takes the matrix of vector x and rows/columns n as input and caches its inverse. 
## Args:
## x: matrix input value. nrow must be equal to ncol. 
## set: function that can change matrix values. 
## get: retrieves matrix input values (x) for main function (make_Cache_Matrix).
## inv: inverse of square matrix generated by solve() function. Set to NULL in local environment and, if input matrix data changes, set to NULL in parent environments. 
## set_inverse: stores inverse matrix value in make_Cache_Matrix.
## get_inverse: retrieves inverse matrix value from make_Cache_Matrix
## list(): creates list of 4 functions so that make_Cache_Matrix

makeCacheMatrix <- function(x = matrix()) {
         inv <- NULL         
         set <- function(y) {             
         x <<- y                 
         inv <<- NULL         
}         
        get <- function() x                
        set_inverse <- function(solve) inv <<- solve       
get_inverse <- function() inv         
        list(set = set, get = get,              
        set_inverse = set_inverse,              
        get_inverse = get_inverse)
}

## cacheSolve checks if an inverse matrix object is stored in memory. If it is, the function returns a message and the inverse matrix value. If inv cannot be found, the function retrieves the matrix from the Make_Cache_Matrix function and creates an inverse matrix.

cacheSolve <- function(x, ...) {
               inv <- x$get_inverse()
                   if(is.null(inv)) {
                   data <- x$get() x
                   inv <- solve(data) 
                   x$set_inverse() inv 
}
        else {             message("getting cached data")         }          print(inv)           
}


